### ISSUE TITLE
Unable to install and/or start

### ISSUE THREAD

**Issue by sanfordredlich** [rubyamf/rocketamf#10]
Thanks for working on this. I'm using 
- ruby 1.9.3p0 (2011-10-30) [i386-mingw32] on Win 7 x64  

When I did an initial bundle install using 
- gem "RocketAMF", :git => "git://github.com/rubyamf/rocketamf.git"

I got a false native extension building error as if DevKit wasn't installed, similar to the one Stephen reported here:
- https://github.com/carlhuda/bundler/issues/1120

So I tried 
- gem "RocketAMF"

That installs fine but then on server startup gives this error:
- Uncaught exception: uninitialized constant RocketAMF::MappingSet

Is there a version that works with Ruby 1.9.3 or would I have to go back to 1.9.2 or what?

Thanks for any tips!
- Sanford

**Comment by sanfordredlich** [comment]
PS - here's the console output when using
- gem "RocketAMF", :git => "git://github.com/rubyamf/rocketamf.git"

C:\Ruby193\bin\ruby.exe -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) C:\Ruby193\bin/bundle install
Updating git://github.com/rubyamf/rocketamf.git
Fetching source index for http://rubygems.org/
Using rake (0.9.2.2) 
Using RocketAMF (1.0.0) from git://github.com/rubyamf/rocketamf.git (at master) with native extensions 
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

```
    C:/Ruby193/bin/ruby.exe extconf.rb 
```

checking for rb_str_encode()... **\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=C:/Ruby193/bin/ruby
    --enable-sort-props
    --disable-sort-props
C:/Ruby193/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from C:/Ruby193/lib/ruby/1.9.1/mkmf.rb:461:in`try_link0'
    from C:/Ruby193/lib/ruby/1.9.1/mkmf.rb:476:in `try_link'
    from C:/Ruby193/lib/ruby/1.9.1/mkmf.rb:619:in`try_func'
    from C:/Ruby193/lib/ruby/1.9.1/mkmf.rb:894:in `block in have_func'
    from C:/Ruby193/lib/ruby/1.9.1/mkmf.rb:790:in`block in checking_for'
    from C:/Ruby193/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postpone'
    from C:/Ruby193/lib/ruby/1.9.1/mkmf.rb:254:in`open'
    from C:/Ruby193/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
    from C:/Ruby193/lib/ruby/1.9.1/mkmf.rb:254:in`open'
    from C:/Ruby193/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
    from C:/Ruby193/lib/ruby/1.9.1/mkmf.rb:789:in`checking_for'
    from C:/Ruby193/lib/ruby/1.9.1/mkmf.rb:893:in `have_func'
    from extconf.rb:14:in`<main>'

**Comment by waseem** [comment]
@sanfordredlich I'm late to the party it seems. Did you figure out a solution for this? I have the same issue.

**Comment by awesome** [comment]
```ruby
# ~/.gem/ruby/2.1.9/gems/RocketAMF-0.2.1/lib/rocketamf.rb
# at bottom of file
module RocketAMF
   class MappingSet < RocketAMF::ClassMapping::MappingSet
   end
end
```
